---
output: pdf_document
header-includes: 
- \usepackage{color} 
- \usepackage{booktabs}
- \usepackage[table,xcdraw]{xcolor}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tinytex)
```

\setlength{\leftskip}{1cm}
###     Extract from: 

   _Bradley Efron and Trevor Hastie_   
   _Computer Age Statistical Inference: Algorithms, Evidence, and Data Science_
   _Cambridge University Press, 2016_
   _htps://web.standford.edu/~hastie/CASI_files/PDF/casi.pdf_  \newline
\newline
\newline
\newline    
        

\setlength{\leftskip}{0cm}

\qquad Modern Bayesian practice uses various strategies to consruct an appropriate "prior" *$g(\mu)$* in the absence of prior experience, leaving many statisticians unconvinced by the resulting Bayesian inferences. Our second example ilustrates the difficulty. 

  
\textcolor{blue}{Table 3.1} *Scores from two tests taken by 22 students,* \textcolor{green}{mechanics} *and* \textcolor{green}{vectors}. 
\newline

\begin{center}
\begin{tabular}{@{}llllllllllll@{}}
                                 & 1  & 2  & 3  & 4  & 5  & 6  & 7  & 8  & 9  & 10 & 11 \\ \midrule
{\color[HTML]{036400} mechanics} & 7  & 44 & 49 & 59 & 34 & 46 & 0  & 32 & 49 & 52 & 44 \\
{\color[HTML]{036400} vectors}   & 51 & 69 & 41 & 70 & 42 & 40 & 40 & 45 & 57 & 64 & 61 \\ \midrule
                                 & 12 & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20 & 21 & 22 \\ \midrule
{\color[HTML]{036400} mechanics} & 36 & 42 & 5  & 22 & 18 & 41 & 48 & 31 & 42 & 46 & 63 \\
{\color[HTML]{036400} vectors}   & 59 & 60 & 30 & 58 & 51 & 63 & 38 & 42 & 69 & 49 & 63 \\ \bottomrule
\end{tabular}
\end{center}

## `

  Table 3.1 shows the scores on two tests, \textcolor{green}{mechanics} and \textcolor{green}{vectors}, achieved by *n* = 22 students. The sample correlation coefficient between the two scores is $\hat{\Theta}$ = 0.498,   
  

$$\hat{\theta} = \sum_{i=1}^{22}(m_{i} - \bar{m})(v_{i} - \bar{v})/\left [\sum_{i=1}^{22}(m_{i} - \bar{m})^{2}\sum_{i=1}^{22}(v_{i} - \bar{v})^{2}  \right ]^{1/2}$$

  



    

